# Generated by Django 2.0.1 on 2018-01-19 04:06

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(default=0)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar', models.ImageField(default='avt.png', null=True, upload_to=app.models.content_file_name)),
                ('isAdmin', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('sq_ft', models.IntegerField(default=0)),
                ('price', models.FloatField(blank=True, default=None, null=True)),
                ('option', models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent')], default='buy', max_length=9)),
                ('fields', models.CharField(choices=[('resi', 'Residential'), ('land', 'Land'), ('comm', 'Commercial')], default='buy', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Locality')),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AddField(
            model_name='information',
            name='society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Society'),
        ),
    ]
